### PR TITLE
Local built-in RBAC assignment for logged in user

### PR DESCRIPTION
**Pull request by SenthuranSivananthan**
* Instructions for granting key management permissions to the logged in user.  This is required since an administrator does not have access to key management operations.
* Link to the local built-in roles to help users decide on the appropriate role.

### CODE REVIEW

**Comment by svenkata9** [comment]
@SenthuranSivananthan Will this resolve #14?

**Comment by SenthuranSivananthan** [comment]
@svenkata9 I believe it would help.  Can you share your role assignment command?

Here's mine:

```
oid=$(az ad signed-in-user show --query id -o tsv)

az keyvault create --hsm-name "hsmdemo" --resource-group "kvhsm" --location "eastus" --administrators $oid --retention-days 7 --enable-purge-protection false

az keyvault role assignment create  --hsm-name hsmdemo --assignee $oid  --scope / --role "Managed HSM Crypto User"

```

**Comment by svenkata9** [comment]
Thanks for the quick response, Senthuran. Something like this.

If this works for the logged in user (through `az login`) it will greatly help.

```
az keyvault role assignment create --hsm-name svenkat9-akv-mhsm --role "Managed HSM Crypto User" --assignee xyz@intel.com --scope /
{
  "id": "/providers/Microsoft.Authorization/roleAssignments/f378bd4c-2300-4d9f-932f-6a41e640ad3f",
  "name": "f378bd4c-2300-4d9f-932f-6a41e640ad3f",
  "principalId": "2775cb0f-a5cc-41bf-bbac-f47a756dd375",
  "principalName": "xyz@intel.com",
  "principalType": "User",
  "roleDefinitionId": "Microsoft.KeyVault/providers/Microsoft.Authorization/roleDefinitions/21dbd100-6940-42c2-9190-5d6cb909625b",
  "roleName": "Managed HSM Crypto User",
  "scope": "/",
  "type": "Microsoft.Authorization/roleAssignments"
}
```

**Comment by SenthuranSivananthan** [comment]
> Thanks for the quick response, Senthuran. Something like this.
> 
> If this works for the logged in user (through `az login`) it will greatly help.
> 
> ```
> az keyvault role assignment create --hsm-name svenkat9-akv-mhsm --role "Managed HSM Crypto User" --assignee xyz@intel.com --scope /
> {
>   "id": "/providers/Microsoft.Authorization/roleAssignments/f378bd4c-2300-4d9f-932f-6a41e640ad3f",
>   "name": "f378bd4c-2300-4d9f-932f-6a41e640ad3f",
>   "principalId": "2775cb0f-a5cc-41bf-bbac-f47a756dd375",
>   "principalName": "xyz@intel.com",
>   "principalType": "User",
>   "roleDefinitionId": "Microsoft.KeyVault/providers/Microsoft.Authorization/roleDefinitions/21dbd100-6940-42c2-9190-5d6cb909625b",
>   "roleName": "Managed HSM Crypto User",
>   "scope": "/",
>   "type": "Microsoft.Authorization/roleAssignments"
> }
> ```

This should work as long as you can pass along the oauth token to the HSM.  In my tests, I was use `az keyvault key create` which did this on my behalf.

Looking at https://github.com/SenthuranSivananthan/AzureKeyVaultManagedHSMEngine/blob/docs/src/dllmain.c#L195 & https://github.com/microsoft/AzureKeyVaultManagedHSMEngine/blob/main/src/curl.c#L73, I don't see any reference to using the local user's token as fallback.

Could you use the REST APIs for your scenario?  https://learn.microsoft.com/en-us/rest/api/keyvault/#cryptographic-operations-key-vaultmanaged-hsm

Therefore, I think it's best to keep your issue open until the maintainers respond.

**Comment by svenkata9** [comment]
Sure. I will keep it open. I use [Azure Key Vault Python SDK](https://azuresdkdocs.blob.core.windows.net/$web/python/azure-keyvault-keys/latest/azure.keyvault.keys.crypto.html#azure.keyvault.keys.crypto.CryptographyClient) for key creation and retrieval.

This is our actual implementation for using AKV - https://github.com/gramineproject/contrib/blob/5b18ebeceb52cb72d5367271d76126f3be7e5f6a/Integrations/hsm-akv/gramine-sgx-akv-sign#L17

**Comment by liupums** [comment]
the current engine will always use the managed identity from IMDS. What is the ask here?

see  https://github.com/microsoft/AzureKeyVaultManagedHSMEngine/blob/main/src/curl.c
int GetAccessTokenFromIMDS(const char *type, MemoryStruct *accessToken)

**Review by liupums — APPROVED** [review]

**Comment by svenkata9** [comment]
> 

@liupums The ask here is to allow the logged in user to be authenticated to use AKV OpenSSL engine (who doesn't have managed identity enabled).

**Comment by liupums** [comment]
The support is added for windows only, the doc is here
https://github.com/microsoft/AzureKeyVaultManagedHSMEngine/blob/main/samples/openssl/UseAzureCliCredential.md

**Comment by svenkata9** [comment]
Thanks @liupums. What does it take to enable it for Linux? I read through the link above and at least looks (except for PowerShell) OS agnostic.

**Comment by liupums** [comment]
> Thanks @liupums. What does it take to enable it for Linux? I read through the link above and at least looks (except for PowerShell) OS agnostic.

Linux support is added and tested in WSL. Updated the doc https://github.com/microsoft/AzureKeyVaultManagedHSMEngine/blob/main/samples/openssl/UseAzureCliCredential.md

**Comment by svenkata9** [comment]
@liupums I just tested it in my system. It still seems to depend on managed identity still. Here is the output from my execution. Am I missing something here? I am able to use the same key in AKV-MHSM to sign using AKV Python SDK API.

```
svenkat9@172.17.0.1
/home/svenkat9/AzureKeyVaultManagedHSMEngine/samples/openssl
openssl (main) $ echo $AKVKEY
managedHsm:svenkat9-akv-mhsm-1:sv-sgx-sign-key

svenkat9@172.17.0.1
/home/svenkat9/AzureKeyVaultManagedHSMEngine/samples/openssl
openssl (main) $ openssl pkeyutl -engine e_akv -sign -keyform engine -inkey $AKVKEY -in hash256 -out hash256.sig -pkeyopt rsa_padding_mode:pss -pkeyopt digest:sha256
engine "e_akv" set.
[e] GetAccessTokenFromIMDS curl.c(198) An access_token field was not found in the IDMS endpoint response. Is a managed identity available?

[e] vaultErrorLog curl.c(27) Vault error - unknown.

cannot load Private Key from engine
140659960553920:error:26096080:engine routines:ENGINE_load_private_key:failed loading private key:../crypto/engine/eng_pkey.c:78:
unable to load Private Key
pkeyutl: Error initializing context

**********************************
svenkat9@172.17.0.1
/home/svenkat9/AzureKeyVaultManagedHSMEngine/samples/openssl
openssl (main) $ az account show
{
  "environmentName": "AzureCloud",
  "homeTenantId": "xxxxxxxxxxxxxx",
  "id": "xxxxxxxxxxxxxxxx",
  "isDefault": true,
  "managedByTenants": [],
  "name": "xxxxxxxxxxxxxxx",
  "state": "Enabled",
  "tenantId": "xxxxxxxxxxxxx",
  "user": {
    "name": "xxxxxxxx@yyyy.com",
    "type": "user"
  }
}
```

**Comment by svenkata9** [comment]
I made a mistake. I assumed that I have to replace the https://managedhsm.azure.net with my AKV MHSM URL. By executing the command that you provided in the document (with replaced tenant ID) and maintaining the same `--resource` (as https://managedhsm.azure.net), I am able to now get and set the AZURE_CLI_ACCESS_TOKEN. But, when executing the openssl command with engine, I encountered a crash.

```
/home/svenkat9/AzureKeyVaultManagedHSMEngine/samples/openssl
openssl (main) $ openssl pkeyutl -engine e_akv -sign -keyform engine -inkey $AKVKEY -in hash256 -out hash256.sig -pkeyopt rsa_padding_mode:pss -pkeyopt digest:sha256
engine "e_akv" set.
[i] GetAccessTokenFromIMDS curl.c(99) Environment variable AZURE_CLI_ACCESS_TOKEN defined [7735]

[e] vaultErrorLog curl.c(23) Vault error {"code":"Unauthorized","message":"Error decoding or parsing JWT components (Activity ID: c52dc3f4-8c33-11ed-b2df-6045bdadf53e)"}

*** stack smashing detected ***: <unknown> terminated
Aborted (core dumped)
```

**Comment by liupums** [comment]
from the error message, it seems your token is corrupted or not set correctly.
"message":"Error decoding or parsing JWT components (Activity ID: c52dc3f4-8c33-11ed-b2df-6045bdadf53e)"
Are you following the steps in https://github.com/microsoft/AzureKeyVaultManagedHSMEngine/blob/main/samples/openssl/UseAzureCliCredential.md

Also, I did not try "openssl pkeyutl -engine e_akv -sign" before, there might be an error case which is not handled properly in the engine. If you have time, could you fix it in the engine code?

Thanks!

**Comment by liupums** [comment]
> Yes, @liupums, I did follow the steps in this document. I can try to take a look into the openssl engine code, but I wanted to first make sure this is not something that I only see. Could you just execute the `pkeyutl` on your side to see if things work on your side? If it does, it could be some setup issue on my side (which I still don't understand because I followed the steps you listed).

I perform the pkeyutl on my side and all worked fine.


```
puliu@PopDevBox:~/AzureKeyVaultManagedHSMEngine/src/build$ az account set --name "$AZURE_SUBS"
puliu@PopDevBox:~/AzureKeyVaultManagedHSMEngine/src/build$ t=$(az account get-access-token --output json --tenant $AZURE_TENANT --resource https://managedhsm.azure.net | jq -r '.accessToken')
puliu@PopDevBox:~/AzureKeyVaultManagedHSMEngine/src/build$ export AZURE_CLI_ACCESS_TOKEN=$t
puliu@PopDevBox:~/AzureKeyVaultManagedHSMEngine/src/build$ export AZURE_RSAKEY="managedHsm:ManagedHSMOpenSSLEngine:myrsakey"
puliu@PopDevBox:~/AzureKeyVaultManagedHSMEngine/src/build$ echo "rsa key Managed HSM test" > readme.md
puliu@PopDevBox:~/AzureKeyVaultManagedHSMEngine/src/build$ date >> readme.md
puliu@PopDevBox:~/AzureKeyVaultManagedHSMEngine/src/build$ openssl pkey -engine e_akv -inform engine -in $AZURE_RSAKEY -pubout -text -out leafpubkey.pem
engine "e_akv" set.
[i] GetAccessTokenFromIMDS curl.c(99) Environment variable AZURE_CLI_ACCESS_TOKEN defined [2058]

puliu@PopDevBox:~/AzureKeyVaultManagedHSMEngine/src/build$ openssl dgst -binary -sha256 -out hash256 readme.md
puliu@PopDevBox:~/AzureKeyVaultManagedHSMEngine/src/build$ openssl pkeyutl -engine e_akv -sign -keyform engine -inkey $AZURE_RSAKEY -in hash256 -out hash256.sig -pkeyopt digest:sha256 -pkeyopt rsa_padding_mode:pss
engine "e_akv" set.
[i] GetAccessTokenFromIMDS curl.c(99) Environment variable AZURE_CLI_ACCESS_TOKEN defined [2058]

[i] GetAccessTokenFromIMDS curl.c(99) Environment variable AZURE_CLI_ACCESS_TOKEN defined [2058]

puliu@PopDevBox:~/AzureKeyVaultManagedHSMEngine/src/build$ openssl pkeyutl -verify -pubin -inkey leafpubkey.pem -in hash256 -sigfile hash256.sig -pkeyopt digest:sha256  -pkeyopt rsa_padding_mode:pss
Signature Verified Successfully
puliu@PopDevBox:~/AzureKeyVaultManagedHSMEngine/src/build$ openssl pkeyutl -engine e_akv -sign -keyform engine -inkey $AZURE_RSAKEY -in hash256 -out hash256.sig.pss -pkeyopt digest:sha256 -pkeyopt rsa_padding_mode:pss
engine "e_akv" set.
[i] GetAccessTokenFromIMDS curl.c(99) Environment variable AZURE_CLI_ACCESS_TOKEN defined [2058]

[i] GetAccessTokenFromIMDS curl.c(99) Environment variable AZURE_CLI_ACCESS_TOKEN defined [2058]

puliu@PopDevBox:~/AzureKeyVaultManagedHSMEngine/src/build$ openssl pkeyutl -verify -pubin -inkey leafpubkey.pem -in hash256 -sigfile hash256.sig.pss -pkeyopt digest:sha256  -pkeyopt rsa_padding_mode:pss
Signature Verified Successfully
puliu@PopDevBox:~/AzureKeyVaultManagedHSMEngine/src/build$ openssl pkeyutl -engine e_akv -sign -keyform engine -inkey $AZURE_RSAKEY -in hash256 -out hash256.sig -pkeyopt digest:sha256
engine "e_akv" set.
[i] GetAccessTokenFromIMDS curl.c(99) Environment variable AZURE_CLI_ACCESS_TOKEN defined [2058]

[i] GetAccessTokenFromIMDS curl.c(99) Environment variable AZURE_CLI_ACCESS_TOKEN defined [2058]

puliu@PopDevBox:~/AzureKeyVaultManagedHSMEngine/src/build$ openssl pkeyutl -verify -pubin -inkey leafpubkey.pem -in hash256 -sigfile hash256.sig -pkeyopt digest:sha256
Signature Verified Successfully
```

**Comment by liupums** [comment]
One possible cause is you are using openssl 3.0. I can reproduce this issue when building the engine with openssl3.0.

you can check by running "openssl version -a"
Here is my output
```
puliu@PopDevBox:~/AzureKeyVaultManagedHSMEngine/src/build$ openssl version -a
OpenSSL 1.1.1f  31 Mar 2020aultManagedHSMEngine/src/build$
built on: Mon Jul  4 11:24:28 2022 UTC
platform: debian-amd64
options:  bn(64,64) rc4(16x,int) des(int) blowfish(ptr)
compiler: gcc -fPIC -pthread -m64 -Wa,--noexecstack -Wall -Wa,--noexecstack -g -O2 -fdebug-prefix-map=/build/openssl-51ig8V/openssl-1.1.1f=. -fstack-protector-strong -Wformat -Werror=format-security -DOPENSSL_TLS_SECURITY_LEVEL=2 -DOPENSSL_USE_NODELETE -DL_ENDIAN -DOPENSSL_PIC -DOPENSSL_CPUID_OBJ -DOPENSSL_IA32_SSE2 -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_MONT5 -DOPENSSL_BN_ASM_GF2m -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DKECCAK1600_ASM -DRC4_ASM -DMD5_ASM -DAESNI_ASM -DVPAES_ASM -DGHASH_ASM -DECP_NISTZ256_ASM -DX25519_ASM -DPOLY1305_ASM -DNDEBUG -Wdate-time -D_FORTIFY_SOURCE=2
OPENSSLDIR: "/usr/lib/ssl"
ENGINESDIR: "/usr/lib/x86_64-linux-gnu/engines-1.1"
Seeding source: os-specific
```



here is my script
please define your own subscription name, tenant, and rsa key in the script. My rsa key is "managedHsm:ManagedHSMOpenSSLEngine:myrsakey"
export AZURE_SUBS="YOUR SUBSCRIPTION NAME"
export AZURE_TENANT="YOUR TENANT"
export AZURE_RSAKEY="YOUR RSA KEY"

```
az login
az account set --name "$AZURE_SUBS"
t=$(az account get-access-token --output json --tenant $AZURE_TENANT --resource https://managedhsm.azure.net | jq -r '.accessToken')
export AZURE_CLI_ACCESS_TOKEN=$t

echo "rsa key Managed HSM test" > readme.md
date >> readme.md
openssl pkey -engine e_akv -inform engine -in $AZURE_RSAKEY -pubout -text -out leafpubkey.pem
openssl dgst -binary -sha256 -out hash256 readme.md
openssl pkeyutl -engine e_akv -sign -keyform engine -inkey $AZURE_RSAKEY -in hash256 -out hash256.sig.pss -pkeyopt digest:sha256 -pkeyopt rsa_padding_mode:pss
openssl pkeyutl -verify -pubin -inkey leafpubkey.pem -in hash256 -sigfile hash256.sig.pss -pkeyopt digest:sha256  -pkeyopt rsa_padding_mode:pss
openssl pkeyutl -engine e_akv -sign -keyform engine -inkey $AZURE_RSAKEY -in hash256 -out hash256.sig -pkeyopt digest:sha256
openssl pkeyutl -verify -pubin -inkey leafpubkey.pem -in hash256 -sigfile hash256.sig -pkeyopt digest:sha256
```

**Pull request merged**
